### ISSUE TITLE
Backward Multi-Grid Deformation

### ISSUE THREAD

**Issue by waveajay** [nie-lang/Multi-Grid-Deep-Homography#11]
can some one tell me where is  Backward Multi-Grid Deformation implemented in the code?

**Comment by nie-lang** [comment]
Please refer to [tf_spatial_transform_local.py](https://github.com/nie-lang/Multi-Grid-Deep-Homography/blob/main/Codes/tf_spatial_transform_local.py). It takes the images and the predicted mesh as the input, and outputs the warped results .

**Comment by waveajay** [comment]
Thanks  @nie-lang 
I referred   tf_spatial_transform_local.py and here is what I understood
1. Homography matrix is calculated for each grid cell. Taking regular mesh as reference and predicted mesh as target
2. Then this homography is applied on the input image
If that is what it is doing,how it is related to Backward Multi-Grid Deformation.I am not able to understand it.

**Comment by nie-lang** [comment]
Well, for the forward deformation, the regular mesh is placed on the target image, and the predicted mesh represents the warped target image. But for the backward deformation, we place a regular mesh on the warped target image and predict the corresponding mesh in the target image. This is the difference between forward deformation and backward deformation.

And we do not adopt the more straightward forward deformation because this process can hard be implemented in a parallel manner. To implement it, we need to know which grid does each pixel in the warped target image belong to. But, it's hard to make it in a concise way.

**Comment by waveajay** [comment]
Thanks @nie-lang  ,but I could not relate it with code.
where do we place regular mesh in the warped target image?
where are we predicting  the grid motions from the reference image domain to the target image domain?

could you please tell where these things are implemented in the [tf_spatial_transform_local.py](https://github.com/nie-lang/Multi-Grid-Deep-Homography/blob/main/Codes/tf_spatial_transform_local.py).

**Comment by nie-lang** [comment]
The parameter $theta$ is the predicted mesh, and the regular mesh can be found in the following function.
![bff5aaedc4c1591dc52f29049e3c9d2](https://user-images.githubusercontent.com/54256137/192140991-621022b3-2897-4016-b409-bfba205beb67.png)
$ori$ is the grids of the regular mesh and $tar$ is the grids of the predicted mesh. We directly calculate the homo for every corresponding grid.

**Comment by waveajay** [comment]
@nie-lang Thank you  I do understand that part.
Here is my confusion, predicted mesh is calculated based transformation of regular mesh of  target image domain to reference image domain. In backward deformation  we are applying that predicted mesh on  target image.

Regular mesh in target image domain transform to predicted mesh in reference image domain. Regulars mesh in reference image domain is predicted mesh in target image domain. Is that the  logic behind calculating the homo from regular mesh to predicted mesh.

**Comment by nie-lang** [comment]
We do apply the predicted mesh on the target image. 

If we directly apply the predicted mesh on the warped target image, we need to determine which grid does each pixel on the warped target image belongs to. Actually, it’s very hard to determine it in a fast parallel manner because the predicted mesh is irregular and even some pixels in the warped target image belong to no grid.

Anyway, if we can determine the belongs parallel, we can also apply the predicted mesh on the warped target image to implement the mesh deformation. If you can do it, please let me know.

**Comment by waveajay** [comment]
@nie-lang
I am in confused . I think I did not put it clearly before . Let try to write it clearly.

case 1
Let us  place a  regular mesh on target image. Now let me focus just on one  cell of the said grid. Let  us call that cell A. We also have the  predicted mesh. We place the predicted mesh on wraped target  image. Cell A has corresponding cell in predicted mesh , let it be A'. We know that A and A'  encloses  same pixels. Let H be homography of A->A'.
then A' = HA and we apply same homography on pixels inside A  to get it's position in wraped image,those pixel reside in A'


Here is  what I don't understand.
case II
Let us  place a  regular mesh on wraped  target image. Now let me focus just on one  cell of the said grid. Let  us call that cell A. We also have the  predicted mesh. We place the predicted mesh on target  image. Cell A has corresponding cell in predicted mesh also,let it be A'.

How can we say that cell A and cell A' enclose same pixels?

or in other words 

if regular mesh in target image domain get converted to predicted mesh in reference image domain.

that why we can say that  predicted  mesh in target image  domain converts to regular mesh in reference image domain?

Please give me a insight to this?

**Comment by nie-lang** [comment]
Well, case 1 is easy to understand and that is what most traditional mesh-based methods have done.

But when it comes to deep learning, it has a new problem. To avoid invalid regions (the black holes in the warped image), we have to adopt backward interpolation to implement the warp. So, we need to determine which cell dose the pixel in the warped image belongs to. In the description of case 1, you just use the forward interpolation.

**Comment by waveajay** [comment]
@nie-lang 
Is there any mathematical proof 
A cell in regular grid over wrapped image enclose  same pixels as  its corresponding  cell in  predicted mesh placed over  target image.
I tried to prove it, but I could not prove it. I  believe backward deformation works on above principle principle.

PS: My confusion is not  why backward deformation is used, but I am looking for an explanation why it works

**Comment by nie-lang** [comment]
Given an arbitrary point p' in the warped target image, we determine which cell it belongs to first. It's easy to do it because we use the Backward Multi-Grid Deformation with a regular mesh on the warped image. Suppose it belongs to c' (the corresponding cell in the target image is c), then we can calculate the homo matrix H between c' and c.  Next, we can locate the corresponding point of p' on the target image by p ~Hp'.

So, in this manner, all the pixels in c' must be from c. To be more rigorous，p might not be a point with integer coordinates, and we use bilinear interpolation to calculate its value.

**Comment by waveajay** [comment]
@nie-lang.I do understand that. We calculated predicted mesh from target image to reference image. Regular mesh in target image is predicted mesh in reference image domain.

### In backward deformation, paper is saying that regular mesh in reference image domain is predicted mesh in target domain.


I don't not understand how it will be.

**Comment by nie-lang** [comment]
First, the reference domain can be regarded as the warped target domain.
Second,  I’m confused by your question. Where does this description appear in the paper?

**Comment by waveajay** [comment]
@nie-lang I am sorry if I misinterpreted fig 6(d).I thought regular mesh in  warped target domain. is predicted mesh in target domain.And in [tf_spatial_transform_local.py](https://github.com/nie-lang/Multi-Grid-Deep-Homography/blob/main/Codes/tf_spatial_transform_local.py).  Homograpy Is calculated between regular mesh and  predicted mesh.

**Comment by nie-lang** [comment]
Well, I do not express such a message in the paper.

Actually, this part is hard to give a clear description. But I think you have got it.

**Comment by waveajay** [comment]
` ## initialize the mesh using H2
    ini_mesh = H2Mesh(H2, patch_size)
    ## calculate the final predicted mesh
    mesh = ini_mesh + mesh_motion

    depth = tf.concat([train_depth, train_depth, train_depth], 3)
    ## warp the image/all-one image/ depth map using mesh
    warp2_H3, one_warp_H3, warp2_depth = tf_spatial_transform_local.transformer(image2_tensor, one, depth, mesh)`

In this code 'mesh' is predicted mesh in wrapped target image domain right

**Comment by waveajay** [comment]
` ## initialize the mesh using H2
    ini_mesh = H2Mesh(H2, patch_size)
    ## calculate the final predicted mesh
    mesh = ini_mesh + mesh_motion
`

**Comment by waveajay** [comment]
`## calculate the final predicted mesh
 mesh = ini_mesh + mesh_motion`

**Comment by waveajay** [comment]
`   ## calculate the final predicted mesh `
 `   mesh = ini_mesh + mesh_motion`
code from [H_model.py](https://github.com/nie-lang/Multi-Grid-Deep-Homography/blob/main/Codes/H_model.py).
This mesh corresponds to predicted mesh in wrapped target domain

This mesh is passed as an argument to [tf_spatial_transform_local.py](https://github.com/nie-lang/Multi-Grid-Deep-Homography/blob/main/Codes/tf_spatial_transform_local.py).Same mesh placed over target image.

So I thought regular mesh in wrapped target corresponds to predicted mesh  in target image domain.

Am I wrong?  
If I am not wrong , I like to know why regular mesh in wrapped target  image corresponds to predicted mesh  in target image domain?

**Comment by nie-lang** [comment]
The mesh in the code is the predicted mesh on the target image, not over the warped target domain.

**Comment by waveajay** [comment]
Thank you @nie-lang
