### ISSUE TITLE
CCL_pytorch

### ISSUE THREAD

**Issue by Romatic-zbj** [nie-lang/Multi-Grid-Deep-Homography#15]
Very nice project! but the implementation of CCL_pytorch that you have created may cause a memory overflow when used, did you try it.
just test it like this.  Looking forward to your reply。
![image](https://github.com/nie-lang/Multi-Grid-Deep-Homography/assets/78793268/46bb08b1-592c-4a86-aead-cfc43b0b4ced)
![image](https://github.com/nie-lang/Multi-Grid-Deep-Homography/assets/78793268/dbdb3284-2034-4935-911e-0bd1c9cd43e1)

**Comment by nie-lang** [comment]
It's recommended to be used in low-resolution feature maps, e.g., 16x16, 32x32.

Its limitation is that it can only calculate the global correlation by searching the whole image. So, it would create a temporary matching map with a resolution of h*w*(h*w). That's the cause of the memory overflow.

**Comment by Romatic-zbj** [comment]
> It's recommended to be used in low-resolution feature maps, e.g., 16x16, 32x32.
> 
> Its limitation is that it can only calculate the global correlation by searching the whole image. So, it would create a temporary matching map with a resolution of h_w_(h*w). That's the cause of the memory overflow.

Oh,Thank you！
